INSERT INTO zipcode VALUES (10199, 'NY', 'NY');
INSERT INTO zipcode VALUES (11256, 'Brooklyn', 'NY');
INSERT INTO zipcode VALUES (12288, 'Boston', 'MA');
INSERT INTO zipcode VALUES (45234, 'Cincinnati', 'OH');
INSERT INTO zipcode VALUES (43216, 'Columbus', 'OH');
INSERT INTO zipcode VALUES (44101, 'Cleveland', 'OH');
INSERT INTO zipcode VALUES (16515, 'Erie', 'PA');
INSERT INTO zipcode VALUES (15290, 'Pittsburgh', 'PA');
INSERT INTO zipcode VALUES (17107, 'Harrisburg', 'PA');
INSERT INTO zipcode VALUES (19104, 'Philadelphia', 'PA');
INSERT INTO zipcode VALUES (60607, 'Chicago', 'IL');
INSERT INTO zipcode VALUES (63155, 'St Louis', 'MO');
INSERT INTO zipcode VALUES (46298, 'Indianapolis', 'IN');
INSERT INTO zipcode VALUES (53201, 'Milwaukee', 'WI');
INSERT INTO zipcode VALUES (87101, 'Albuquerque', 'NM');
INSERT INTO zipcode VALUES (72205, 'Little Rock', 'AR');
INSERT INTO zipcode VALUES (73198, 'Oklahoma City', 'OK');
INSERT INTO zipcode VALUES (75099, 'Coppell', 'TX');
INSERT INTO zipcode VALUES (76161, 'Fort Worth', 'TX');
INSERT INTO zipcode VALUES (77067, 'Houston', 'TX');
INSERT INTO zipcode VALUES (78284, 'San Antonio', 'TX');
INSERT INTO zipcode VALUES (32799, 'Mid-Florida', 'FL');
INSERT INTO zipcode VALUES (33122, 'Miami', 'FL');
INSERT INTO zipcode VALUES (33607, 'Tampa', 'FL');
INSERT INTO zipcode VALUES (21233, 'Baltimore', 'MD');
INSERT INTO zipcode VALUES (23232, 'Richmond', 'VA');
INSERT INTO zipcode VALUES (20066, 'Washington', 'DC');
INSERT INTO zipcode VALUES (29292, 'Columbia', 'SC');
INSERT INTO zipcode VALUES (27676, 'Raleigh', 'NC');
INSERT INTO zipcode VALUES (28228, 'Charlotte', 'NC');
INSERT INTO zipcode VALUES (64108, 'Kansas City', 'MO');
INSERT INTO zipcode VALUES (80266, 'Denver', 'CO');
INSERT INTO zipcode VALUES (84199, 'Salt Lake City', 'UT');
INSERT INTO zipcode VALUES (97208, 'Portland', 'OR');
INSERT INTO zipcode VALUES (98109, 'Seattle', 'WA');
INSERT INTO zipcode VALUES (85026, 'Phoenix', 'AZ');
INSERT INTO zipcode VALUES (89199, 'Las Vegas', 'NV');
INSERT INTO zipcode VALUES (90052, 'Los Angeles', 'CA');
INSERT INTO zipcode VALUES (92199, 'San Diego', 'CA');
INSERT INTO zipcode VALUES (94120, 'San Francisco', 'CA');
INSERT INTO zipcode VALUES (95799, 'West Sacramento', 'CA');
